version: "3.8"

services:
  postgres:
    container_name: nest-todo-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: tododb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres